# example yaml source setup file

# define as many superimposing sources as you want below,
# of types "gaussian_blob", "homogeneous", and "ocean"

# Remove those that are not needed

- distribution: "homogeneous"
  source_component: "z"
  mean_frequency_Hz: 0.05
  standard_deviation_Hz: 0.01
  weight: 0.01
  taper_percent: 1.0
  normalize_spectrum_to_unity: true

- distribution: "ocean"
  source_component: "z"
  mean_frequency_Hz: 0.05
  standard_deviation_Hz: 0.02
  weight: 0.5
  taper_percent: 1.0
  normalize_spectrum_to_unity: true

- distribution: "gaussian_blob"
  source_component: "z"
  center_latlon: [45.0, -4.0]
  sigma_m: 50000
  mean_frequency_Hz: 0.1
  standard_deviation_Hz: 0.015
  only_in_the_ocean: true
  weight: 1.0
  taper_percent: 1.0
  normalize_spectrum_to_unity: true
  normalize_blob_to_unity: true
